# Análisis de productividad con Pandas

## En mi día  a día llevo un control de mi flujo de trabajo con un checklist.

#### Precisamente uso [Todoist](https://todoist.com/app/)

#### Fue entonces que se me ocurrió  analizar cuales eran mis horas donde completaba el mayor número  de tareas, procedí a solicitar  los datos por medio de soporte técnico.

#### Dos días después ellos me envían una copia de todos mis datos en formato CSV, agradezco por este medio su buena amabilidad y colaboración.

## Comenzando con el proyecto

### Importamos la librería y DataSets necesarios

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dir_pandas = '/datasets/drive/Colab Notebooks/Datasets/{}'
todoist=pd.read_csv(dir_pandas.format('todoist.csv'))

### Hacemos una previsualización de nuestros datos

In [ ]:
todoist.sample(10)

,id,project_id,content,checked,in_history,parent_id,child_order,priority,date_string,date_lang,due_date,assigned_by_uid,responsible_uid
112,4928907581,2266134779,organizar,1,1,4.850773e+09,1,1,Jun 22 10:00,es,2021-06-22 13:00:00,NaN,NaN
84,4850757899,2266134748,"Taller ""Introducción al laboratorio de Química...",0,0,NaN,1,1,NaN,en,NaN,NaN,NaN
127,4850777203,2266134826,INFORMATORIO Parte 2,1,1,NaN,0,1,NaN,en,NaN,NaN,NaN
180,4928895773,2266134840,Ir al supermercado,1,1,NaN,26,1,Jun 22 12:30,es,2021-06-22 15:30:00,NaN,NaN
126,4865024187,2266134826,INFORMÁTORIO,0,0,NaN,-1,1,"every tue,thu,fri at 18:00",en,2021-07-22 21:00:00,NaN,NaN
78,4999586013,2205359017,video 18,1,1,NaN,10,1,Jul 18,es,2021-07-19 02:59:59,NaN,NaN
15,4998050335,2205359017,Ir al supermercado,1,1,NaN,1,1,2021-07-17 14:30,en,2021-07-17 17:30:00,NaN,NaN
174,4878626646,2266134840,Ir al trabajo,0,0,NaN,24,1,every wed at 08:00,en,2021-07-28 11:00:00,NaN,NaN
139,5003985194,2266134826,Consultas a una base de datos,0,0,NaN,7,1,Jul 20,es,2021-07-21 02:59:59,NaN,NaN
58,4943749194,2205359017,Home banking,1,1,NaN,5,1,26 jun.,es,2021-06-27 02:59:59,NaN,NaN

#### A simple vista podemos observar que las columnas que nos interesan son "id", "due_date" y "date_string"

#### Vamos a copiar en otro DataFrame solo las columnas que nos interesan.

In [ ]:
copi_todoist=todoist.iloc[:,[0,3,8,10]]
copi_todoist

             id  checked       date_string             due_date
0    4853259314        1  2021-05-24 13:45  2021-05-24 16:45:00
1    4865333837        1  2021-05-28 18:00  2021-05-28 21:00:00
2    4866322129        1  2021-05-29 10:00  2021-05-29 13:00:00
3    4874850044        1       Jun 2 17:39  2021-06-02 20:39:00
4    4886181344        1            5 jun.  2021-06-06 02:59:59
..          ...      ...               ...                  ...
196  4860648836        0               NaN                  NaN
197  4860649810        1               NaN                  NaN
198  4907452649        0               NaN                  NaN
199  4860655860        1               NaN                  NaN
200  4980478716        0               NaN                  NaN

[201 rows x 4 columns]

#### Renombramos las columnas para evitar confusiones.

In [ ]:
copi_todoist.rename(columns={'id':'tarea'}, inplace=True)
copi_todoist.rename(columns={'checked':'completado'}, inplace=True)
copi_todoist.rename(columns={'date_string':'fecha_creacion'}, inplace=True)
copi_todoist.rename(columns={'due_date':'fecha_vencimiento'}, inplace=True)

/shared-libs/python3.7/py/lib/python3.7/site-packages/pandas/core/frame.py:4449: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
copi_todoist.sample(10)

          tarea  completado           fecha_creacion    fecha_vencimiento
113  4852867090           1         2021-05-24 12:00  2021-05-24 15:00:00
193  4860631266           0                      NaN                  NaN
16   5003323033           0                   Jul 24  2021-07-25 02:59:59
49   4939610939           1                  24 jun.  2021-06-25 02:59:59
141  4850779513           1                   May 29  2021-05-30 02:59:59
143  4964316635           0  every 1 months at 12:00  2021-07-26 15:00:00
95   4850768061           1                      NaN                  NaN
138  4964315248           0                      NaN                  NaN
155  4850798378           1               2021-12-01  2021-12-02 02:59:59
69   4999582749           1                   Jul 18  2021-07-19 02:59:59

## Limpiar DataFrame

#### Eliminamos las tareas con fecha en formato nulo "nan"

In [ ]:
clear_todoist=copi_todoist.dropna(axis=0)
clear_todoist

          tarea  completado              fecha_creacion    fecha_vencimiento
0    4853259314           1            2021-05-24 13:45  2021-05-24 16:45:00
1    4865333837           1            2021-05-28 18:00  2021-05-28 21:00:00
2    4866322129           1            2021-05-29 10:00  2021-05-29 13:00:00
3    4874850044           1                 Jun 2 17:39  2021-06-02 20:39:00
4    4886181344           1                      5 jun.  2021-06-06 02:59:59
..          ...         ...                         ...                  ...
187  4970212621           0  every mon,wed,fri at 20:30  2021-07-26 23:30:00
188  4911174400           1                     17 jun.  2021-06-18 02:59:59
189  4988035279           1            2021-07-14 11:30  2021-07-14 14:30:00
190  4988039155           1                Jul 20 11:00  2021-07-20 14:00:00
191  4990924394           1                Jul 15 19:00  2021-07-15 22:00:00

[164 rows x 4 columns]

#### Cambiamos los datos a formato "datatime" y extraemos la hora en una nueva columna

In [ ]:
clear_todoist['fecha_vencimiento']=pd.to_datetime(clear_todoist['fecha_vencimiento'])
clear_todoist['hour']=clear_todoist['fecha_vencimiento'].dt.hour
clear_todoist

/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/shared-libs/python3.7/py-core/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,tarea,completado,fecha_creacion,fecha_vencimiento,hour
0,4853259314,1,2021-05-24 13:45,2021-05-24 16:45:00,16
1,4865333837,1,2021-05-28 18:00,2021-05-28 21:00:00,21
2,4866322129,1,2021-05-29 10:00,2021-05-29 13:00:00,13
3,4874850044,1,Jun 2 17:39,2021-06-02 20:39:00,20
4,4886181344,1,5 jun.,2021-06-06 02:59:59,2
...,...,...,...,...,...
187,4970212621,0,"every mon,wed,fri at 20:30",2021-07-26 23:30:00,23
188,4911174400,1,17 jun.,2021-06-18 02:59:59,2
189,4988035279,1,2021-07-14 11:30,2021-07-14 14:30:00,14
190,4988039155,1,Jul 20 11:00,2021-07-20 14:00:00,14
191,4990924394,1,Jul 15 19:00,2021-07-15 22:00:00,22

## Graficando los datos

In [ ]:
_deepnote_run_altair(clear_todoist, """{"$schema":"https://vega.github.io/schema/vega-lite/v4.json","mark":{"type":"bar","tooltip":{"content":"data"}},"height":220,"autosize":{"type":"fit"},"data":{"name":"placeholder"},"encoding":{"x":{"field":"hour","type":"quantitative","sort":null,"scale":{"type":"linear","zero":false}},"y":{"field":"COUNT(*)","type":"quantitative","sort":null,"aggregate":"count","scale":{"type":"linear","zero":true}},"color":{"field":"completado","type":"quantitative","sort":null,"scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

#### Podemos observar que hay un incremento sospechoso alrededor de las "2 AM".

#### Esto puede deberse a mi horario de sueño y la planificación  del día siguiente, eliminaremos este dato para estar seguros.

In [ ]:
hora_productivas=clear_todoist[clear_todoist['hour']!=2]
hora_productivas

,tarea,completado,fecha_creacion,fecha_vencimiento,hour
0,4853259314,1,2021-05-24 13:45,2021-05-24 16:45:00,16
1,4865333837,1,2021-05-28 18:00,2021-05-28 21:00:00,21
2,4866322129,1,2021-05-29 10:00,2021-05-29 13:00:00,13
3,4874850044,1,Jun 2 17:39,2021-06-02 20:39:00,20
7,4924664413,1,Jun 20 12:00,2021-06-20 15:00:00,15
...,...,...,...,...,...
186,4928894466,1,Jun 24 09:30,2021-06-24 12:30:00,12
187,4970212621,0,"every mon,wed,fri at 20:30",2021-07-26 23:30:00,23
189,4988035279,1,2021-07-14 11:30,2021-07-14 14:30:00,14
190,4988039155,1,Jul 20 11:00,2021-07-20 14:00:00,14
191,4990924394,1,Jul 15 19:00,2021-07-15 22:00:00,22

#### Por último, podemos observar el grafico donde hay mayor cumplimiento de tareas.

In [ ]:
_deepnote_run_altair(hora_productivas, """{"$schema":"https://vega.github.io/schema/vega-lite/v4.json","mark":{"type":"bar","tooltip":{"content":"data"}},"height":220,"autosize":{"type":"fit"},"data":{"name":"placeholder"},"encoding":{"x":{"field":"hour","type":"quantitative","sort":null,"scale":{"type":"linear","zero":false}},"y":{"field":"COUNT(*)","type":"quantitative","sort":null,"aggregate":"count","scale":{"type":"linear","zero":true}},"color":{"field":"tarea","type":"nominal","sort":null,"scale":{"type":"linear","zero":false}}}}""")

alt.Chart(...)

#### En un futuro pienso contrastar  estos datos con mis horas de sueño y asi poder sacar nuevas conclusiones.

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=f96e9fbc-1463-42e7-bb9d-586ef32af440' target="_blank">
<img alt='Created in deepnote.com' style='display:inline;max-height:16px;margin:0px;margin-right:7.5px;' src='' > </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>